#!/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2014 Mathias Teulé <mathias.te@googlemail.com>

## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.databases.mysql import *

metadata = MetaData()


Metering =  Table('Metering', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'value', FLOAT(), primary_key=False),
            Column(u'date', DATE(), primary_key=False),
            Column(u'sensor_id', INTEGER(), primary_key=False),
    ForeignKeyConstraint([u'sensor_id'], [u'test_dia.Sensor.id'], name=u'metering_fk_Sensor_id'),
    )
    
Index(u'metering_fk_Sensor_id', Metering.c.sensor_id, unique=False)


Sensor =  Table('Sensor', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=255), primary_key=False),
            Column(u'description', VARCHAR(length=255), primary_key=False),
            Column(u'high_threshold', FLOAT(), primary_key=False),
            Column(u'low_threshold', FLOAT(), primary_key=False),
            Column(u'min_value', FLOAT(), primary_key=False),
            Column(u'max_value', FLOAT(), primary_key=False),
            Column(u'unit', VARCHAR(length=255), primary_key=False),
            Column(u'unit_label', VARCHAR(length=255), primary_key=False),
            Column(u'unique_key', VARCHAR(length=255), primary_key=False),
            Column(u'bus_adress', VARCHAR(length=255), primary_key=False),
    )


