-- ================================================================================
--   innodb SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   innodb
--   Generated at:      Fri Jan 24 05:17:21 2014
--   Input Files:       model.xmi
-- 
-- ================================================================================

set autocommit = 0 ;

-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi



-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi



-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi



-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Fri Jan 24 05:17:21 2014
--     Input Files:       model.xmi


-- innodb requires a special 'quit' command
commit ;

